version: "3.9"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wd_db:/var/www/html/wordpress
    ports:
      - 80:80
      - 443:443
    networks:
      - web-inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
#    image: wordpress:5.5-fpm-alpine
    # ports:
      # - 9000:9000
    volumes:
      - wd_db:/var/www/html/wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    restart: always
    depends_on:
      - mariadb
    networks:
      - web-inception

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - 3306
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - web-inception

#  adminer:
#    image: adminer
#    restart: always
#    networks:
#      - web-inception
##    ports:
##      - 8080:8080

volumes:
  db_data:
    name: db_data
    driver: local
    driver_opts:
      device: /Users/nbirdper/data/db_data
      type: none
      o: bind
  wd_db:
    name: wp_db
    driver: local
    driver_opts:
      device: /Users/nbirdper/Documents/21/05/Inception/data/wp_db
      type: none
      o: bind


networks:
  web-inception:
    name: 'web-inception'
#    driver: bridge
