version: "3.9"

services:

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wd_db:/var/www/html/wordpress
    ports:
      - 80:80
      - 443:443
    networks:
      - web

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
#    image: wordpress:5.5-fpm-alpine
    ports:
      - 9000:9000
    volumes:
      - wd_db:/var/www/html/wordpress
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    restart: always
    depends_on:
      - mariadb
    networks:
      - web

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    ports:
      - 3306:3306
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - web

  adminer:
    image: adminer
    restart: always
    networks:
      - web
#    ports:
#      - 8080:8080




volumes:
  db_data:
    driver: 'local'
    driver_opts:
      type: 'none'
      device: "/Users/nbirdper/Documents/21/05/Inception/srcs/requirements/db_data"
      o: 'bind'
  wd_db:
    driver: 'local'
    driver_opts:
      type: 'none'
      device: "/Users/nbirdper/Documents/21/05/Inception/srcs/requirements/wp_db"
      o: 'bind'

#TODO: HOME/nbirdper/data/wp
#TODO: HOME/nbirdper/data/db

networks:
  web:
    name: 'web'
#    driver: bridge
