version: "3.9"

services:

  wordpress:
    container_name: wordpress
#    build: ./requirements/wordpress
    image: wordpress:5.5-fpm-alpine
#    ports:
#      - 9000:9000
    volumes:
      - ./requirements/wordpress/tools:/docker-entrypoint.d
      - ./html:/var/www/html
#      - ./requirements/wordpress/conf/www.conf:/etc/php7/php-fpm.d/www.conf
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
#    ports:
#      - 3306:3306
    env_file: .env
    volumes:
      - ./requirements/mariadb/tools:/docker-entrypoint-initdb.d
      - ./requirements/databases/db_data:/var/lib/mysql
    restart: always

  adminer:
    image: adminer
    restart: always
#    ports:
#      - 8080:8080

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    ports:
      - 80:80
      - 443:443


volumes:
  db_data:
  html:

#networks:
#  inception:
#    driver: bridge
